version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/mariadb
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: ${VOLUMES_PATH}/wordpress

networks:
  inception:
