version: '3'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    restart: on-failure
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE
        - WORDPRESS_USER
        - WORDPRESS_PASSWORD
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: on-failure
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html

volumes:
  mariadb_volume:
    driver_opts:
        o: bind
        type: none
        device: ${VOLUMES_PATH}/mariadb
  wordpress_volume:
      driver_opts:
        o: bind
        type: none
        device: ${VOLUMES_PATH}/wordpress

networks:
  inception:
